# Generated by Django 5.1.2 on 2025-11-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='restaurant.ingredient'),
        ),
    ]
